import { ServerConfig, ServerEdition } from "./types/types.d";

export interface ServerTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  edition?: ServerEdition;
  category: "vanilla" | "paper" | "fabric" | "forge" | "neoforge" | "modpack" | "specialty";
  requiresModpack?: boolean;
  config: Partial<ServerConfig>;
}

export const serverTemplates: ServerTemplate[] = [
  // Vanilla
  {
    id: "vanilla-survival",
    name: "vanillaSurvival",
    description: "vanillaSurvivalDesc",
    icon: "grass",
    color: "emerald",
    category: "vanilla",
    config: {
      serverType: "VANILLA",
      gameMode: "survival",
      difficulty: "normal",
      hardcore: false,
      pvp: true,
      maxPlayers: "20",
      spawnAnimals: true,
      spawnMonsters: true,
      spawnNpcs: true,
      generateStructures: true,
      allowNether: true,
      levelType: "minecraft:default",
      onlineMode: true,
      commandBlock: false,
      allowFlight: false,
    },
  },
  {
    id: "vanilla-creative",
    name: "vanillaCreative",
    description: "vanillaCreativeDesc",
    icon: "diamond",
    color: "cyan",
    category: "vanilla",
    config: {
      serverType: "VANILLA",
      gameMode: "creative",
      difficulty: "peaceful",
      hardcore: false,
      pvp: false,
      maxPlayers: "20",
      spawnAnimals: true,
      spawnMonsters: false,
      spawnNpcs: true,
      generateStructures: true,
      allowNether: true,
      levelType: "minecraft:default",
      onlineMode: true,
      commandBlock: true,
      allowFlight: true,
    },
  },
  {
    id: "vanilla-hardcore",
    name: "vanillaHardcore",
    description: "vanillaHardcoreDesc",
    icon: "spawner",
    color: "red",
    category: "vanilla",
    config: {
      serverType: "VANILLA",
      gameMode: "survival",
      difficulty: "hard",
      hardcore: true,
      pvp: true,
      maxPlayers: "10",
      spawnAnimals: true,
      spawnMonsters: true,
      spawnNpcs: true,
      generateStructures: true,
      allowNether: true,
      levelType: "minecraft:default",
      onlineMode: true,
      commandBlock: false,
      allowFlight: false,
    },
  },
  // Paper
  {
    id: "paper-performance",
    name: "paperPerformance",
    description: "paperPerformanceDesc",
    icon: "paper",
    color: "blue",
    category: "paper",
    config: {
      serverType: "PAPER",
      gameMode: "survival",
      difficulty: "normal",
      hardcore: false,
      pvp: true,
      maxPlayers: "50",
      spawnAnimals: true,
      spawnMonsters: true,
      spawnNpcs: true,
      generateStructures: true,
      allowNether: true,
      levelType: "minecraft:default",
      onlineMode: true,
      commandBlock: false,
      allowFlight: false,
      useAikarFlags: true,
      viewDistance: "10",
      simulationDistance: "8",
    },
  },
  {
    id: "paper-crossplay",
    name: "paperCrossplay",
    description: "paperCrossplayDesc",
    icon: "paper",
    color: "cyan",
    category: "paper",
    config: {
      serverType: "PAPER",
      gameMode: "survival",
      difficulty: "normal",
      hardcore: false,
      pvp: true,
      maxPlayers: "20",
      spawnAnimals: true,
      spawnMonsters: true,
      spawnNpcs: true,
      generateStructures: true,
      allowNether: true,
      levelType: "minecraft:default",
      onlineMode: true,
      commandBlock: false,
      allowFlight: false,
      extraPorts: ["19132:19132/udp"],
      envVars:
        "PLUGINS=https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot,https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot,https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/5.9.1/PAPER/ViaVersion-5.9.1.jar",
    },
  },
  {
    id: "skyblock",
    name: "skyblock",
    description: "skyblockDesc",
    icon: "chest",
    color: "green",
    category: "specialty",
    config: {
      serverType: "PAPER",
      gameMode: "survival",
      difficulty: "normal",
      hardcore: false,
      pvp: false,
      maxPlayers: "20",
      spawnAnimals: true,
      spawnMonsters: true,
      spawnNpcs: false,
      generateStructures: false,
      allowNether: true,
      levelType: "minecraft:flat",
      onlineMode: true,
      commandBlock: true,
      allowFlight: false,
    },
  },
  {
    id: "pvp-arena",
    name: "pvpArena",
    description: "pvpArenaDesc",
    icon: "diamond-pickaxe",
    color: "orange",
    category: "specialty",
    config: {
      serverType: "PAPER",
      gameMode: "adventure",
      difficulty: "normal",
      hardcore: false,
      pvp: true,
      maxPlayers: "32",
      spawnAnimals: false,
      spawnMonsters: false,
      spawnNpcs: false,
      generateStructures: false,
      allowNether: false,
      levelType: "minecraft:flat",
      onlineMode: true,
      commandBlock: true,
      allowFlight: false,
    },
  },
  {
    id: "peaceful-paradise",
    name: "peacefulParadise",
    description: "peacefulParadiseDesc",
    icon: "golden-apple",
    color: "yellow",
    category: "specialty",
    config: {
      serverType: "VANILLA",
      gameMode: "survival",
      difficulty: "peaceful",
      hardcore: false,
      pvp: false,
      maxPlayers: "20",
      spawnAnimals: true,
      spawnMonsters: false,
      spawnNpcs: true,
      generateStructures: true,
      allowNether: true,
      levelType: "minecraft:default",
      onlineMode: true,
      commandBlock: false,
      allowFlight: false,
    },
  },
  {
    id: "amplified-world",
    name: "amplifiedWorld",
    description: "amplifiedWorldDesc",
    icon: "emerald",
    color: "purple",
    category: "specialty",
    config: {
      serverType: "VANILLA",
      gameMode: "survival",
      difficulty: "normal",
      hardcore: false,
      pvp: true,
      maxPlayers: "15",
      spawnAnimals: true,
      spawnMonsters: true,
      spawnNpcs: true,
      generateStructures: true,
      allowNether: true,
      levelType: "minecraft:amplified",
      onlineMode: true,
      commandBlock: false,
      allowFlight: false,
      maxMemory: "4G",
    },
  },
  // Fabric
  {
    id: "fabric-vanilla",
    name: "fabricVanilla",
    description: "fabricVanillaDesc",
    icon: "crafting-table",
    color: "cyan",
    category: "fabric",
    config: {
      serverType: "FABRIC",
      gameMode: "survival",
      difficulty: "normal",
      hardcore: false,
      pvp: true,
      maxPlayers: "20",
      spawnAnimals: true,
      spawnMonsters: true,
      spawnNpcs: true,
      generateStructures: true,
      allowNether: true,
      levelType: "minecraft:default",
      onlineMode: true,
      commandBlock: false,
      allowFlight: false,
    },
  },
  {
    id: "fabric-creative",
    name: "fabricCreative",
    description: "fabricCreativeDesc",
    icon: "crafting-table",
    color: "blue",
    category: "fabric",
    config: {
      serverType: "FABRIC",
      gameMode: "creative",
      difficulty: "peaceful",
      hardcore: false,
      pvp: false,
      maxPlayers: "20",
      spawnAnimals: true,
      spawnMonsters: false,
      spawnNpcs: true,
      generateStructures: true,
      allowNether: true,
      levelType: "minecraft:default",
      onlineMode: true,
      commandBlock: true,
      allowFlight: true,
    },
  },
  // Forge
  {
    id: "forge-vanilla",
    name: "forgeVanilla",
    description: "forgeVanillaDesc",
    icon: "anvil",
    color: "orange",
    category: "forge",
    config: {
      serverType: "FORGE",
      gameMode: "survival",
      difficulty: "normal",
      hardcore: false,
      pvp: true,
      maxPlayers: "20",
      spawnAnimals: true,
      spawnMonsters: true,
      spawnNpcs: true,
      generateStructures: true,
      allowNether: true,
      levelType: "minecraft:default",
      onlineMode: true,
      commandBlock: false,
      allowFlight: false,
    },
  },
  {
    id: "forge-creative",
    name: "forgeCreative",
    description: "forgeCreativeDesc",
    icon: "anvil",
    color: "yellow",
    category: "forge",
    config: {
      serverType: "FORGE",
      gameMode: "creative",
      difficulty: "peaceful",
      hardcore: false,
      pvp: false,
      maxPlayers: "20",
      spawnAnimals: true,
      spawnMonsters: false,
      spawnNpcs: true,
      generateStructures: true,
      allowNether: true,
      levelType: "minecraft:default",
      onlineMode: true,
      commandBlock: true,
      allowFlight: true,
    },
  },
  // Neoforge
  {
    id: "neoforge-vanilla",
    name: "neoforgeVanilla",
    description: "neoforgeVanillaDesc",
    icon: "redstone",
    color: "purple",
    category: "neoforge",
    config: {
      serverType: "NEOFORGE",
      gameMode: "survival",
      difficulty: "normal",
      hardcore: false,
      pvp: true,
      maxPlayers: "20",
      spawnAnimals: true,
      spawnMonsters: true,
      spawnNpcs: true,
      generateStructures: true,
      allowNether: true,
      levelType: "minecraft:default",
      onlineMode: true,
      commandBlock: false,
      allowFlight: false,
    },
  },
  // Modpacks
  {
    id: "modrinth-modpack",
    name: "modrinthModpack",
    description: "modrinthModpackDesc",
    icon: "netherite-ingot",
    color: "emerald",
    category: "modpack",
    requiresModpack: true,
    config: {
      serverType: "MODRINTH",
      gameMode: "survival",
      difficulty: "normal",
      hardcore: false,
      pvp: true,
      maxPlayers: "20",
      spawnAnimals: true,
      spawnMonsters: true,
      spawnNpcs: true,
      generateStructures: true,
      allowNether: true,
      levelType: "minecraft:default",
      onlineMode: true,
      commandBlock: false,
      allowFlight: false,
      modrinthModpack: "",
      modrinthDownloadDependencies: "required",
      modrinthDefaultVersionType: "release",
      maxMemory: "4G",
    },
  },
  {
    id: "curseforge-modpack",
    name: "curseforgeModpack",
    description: "curseforgeModpackDesc",
    icon: "enchanted-book",
    color: "orange",
    category: "modpack",
    requiresModpack: true,
    config: {
      serverType: "AUTO_CURSEFORGE",
      gameMode: "survival",
      difficulty: "normal",
      hardcore: false,
      pvp: true,
      maxPlayers: "20",
      spawnAnimals: true,
      spawnMonsters: true,
      spawnNpcs: true,
      generateStructures: true,
      allowNether: true,
      levelType: "minecraft:default",
      onlineMode: true,
      commandBlock: false,
      allowFlight: false,
      cfMethod: "url",
      cfUrl: "",
      cfSlug: "",
      cfFile: "",
      maxMemory: "4G",
    },
  },
];

// Bedrock Edition Templates
export const bedrockTemplates: ServerTemplate[] = [
  {
    id: "bedrock-survival",
    name: "bedrockSurvival",
    description: "bedrockSurvivalDesc",
    icon: "grass",
    color: "green",
    category: "vanilla",
    edition: "BEDROCK",
    config: {
      edition: "BEDROCK",
      serverType: "VANILLA",
      gameMode: "survival",
      difficulty: "normal",
      maxPlayers: "10",
      onlineMode: true,
      allowCheats: false,
      defaultPlayerPermissionLevel: "member",
      port: "19132",
    },
  },
  {
    id: "bedrock-creative",
    name: "bedrockCreative",
    description: "bedrockCreativeDesc",
    icon: "diamond",
    color: "cyan",
    category: "vanilla",
    edition: "BEDROCK",
    config: {
      edition: "BEDROCK",
      serverType: "VANILLA",
      gameMode: "creative",
      difficulty: "peaceful",
      maxPlayers: "10",
      onlineMode: true,
      allowCheats: true,
      defaultPlayerPermissionLevel: "operator",
      port: "19132",
    },
  },
  {
    id: "bedrock-family",
    name: "bedrockFamily",
    description: "bedrockFamilyDesc",
    icon: "golden-apple",
    color: "yellow",
    category: "specialty",
    edition: "BEDROCK",
    config: {
      edition: "BEDROCK",
      serverType: "VANILLA",
      gameMode: "survival",
      difficulty: "easy",
      maxPlayers: "8",
      onlineMode: false,
      allowCheats: true,
      defaultPlayerPermissionLevel: "member",
      whiteList: true,
      port: "19132",
    },
  },
];

// Combined templates for UI
export const allTemplates: ServerTemplate[] = [...serverTemplates, ...bedrockTemplates];

export const getTemplateById = (id: string): ServerTemplate | undefined => {
  return allTemplates.find((t) => t.id === id);
};

export const getTemplatesByEdition = (edition: ServerEdition): ServerTemplate[] => {
  if (edition === "BEDROCK") {
    return bedrockTemplates;
  }
  return serverTemplates;
};
